apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockersample-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DockerSample
  template:
    metadata:
      labels:
        app: DockerSample
    spec:
      containers:
      - name: dockersamplerepos
        image: samplecr.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: dockersample
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: DockerSample